services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: larios
      POSTGRES_USER: postgres
      POSTGRES_DB: control
    volumes:
      - vac:/var/lib/postgresql/data
  frontend:
    build: ./frontend
    ports:
      - 5173:5173
  backend:
    build: ./backend
    ports:
      - 8000:8000
    environment:
      DATABASE_HOSTNAME: postgres
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: larios
      DATABASE_NAME: control
      DATABASE_USERNAME: postgres
      SECRET_kEY: bbk3t27c4y
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 180
      DOMAIN_NAME: http://127.0.0.1:8000
    depends_on:
      - postgres
volumes:
  vac:
      

